#ifndef LMME_COMMAND_COMMAND_H
#define LMME_COMMAND_COMMAND_H

#include <glib.h>

typedef struct _LmmeApp LmmeApp;

typedef enum {
    LMME_COMMAND_CATEGORY_FILE,
    LMME_COMMAND_CATEGORY_EDIT,
    LMME_COMMAND_CATEGORY_VIEW,
    LMME_COMMAND_CATEGORY_BUFFER,
    LMME_COMMAND_CATEGORY_WORKSPACE
} LmmeCommandCategory;

typedef enum {
    LMME_COMMAND_HANDLER_OPEN,
    LMME_COMMAND_HANDLER_SAVE,
    LMME_COMMAND_HANDLER_QUIT,
    LMME_COMMAND_HANDLER_NEW_FILE,
    LMME_COMMAND_HANDLER_NEW_FOLDER,
    LMME_COMMAND_HANDLER_RENAME,
    LMME_COMMAND_HANDLER_DELETE,
    LMME_COMMAND_HANDLER_TOGGLE_SIDEBAR,
    LMME_COMMAND_HANDLER_TOGGLE_PREVIEW,
    LMME_COMMAND_HANDLER_ZOOM_IN,
    LMME_COMMAND_HANDLER_ZOOM_OUT,
    LMME_COMMAND_HANDLER_ZOOM_RESET,
    LMME_COMMAND_HANDLER_FOCUS_MODE,
    LMME_COMMAND_HANDLER_CLOSE_TAB,
    LMME_COMMAND_HANDLER_CLOSE_OTHER_TABS,
    LMME_COMMAND_HANDLER_CLOSE_TABS_RIGHT,
    LMME_COMMAND_HANDLER_CLOSE_TABS_LEFT,
    LMME_COMMAND_HANDLER_CLOSE_ALL_TABS,
    LMME_COMMAND_HANDLER_COPY_RELATIVE_PATH,
    LMME_COMMAND_HANDLER_COPY_FULL_PATH,
    LMME_COMMAND_HANDLER_NEXT_TAB,
    LMME_COMMAND_HANDLER_PREVIOUS_TAB,
    LMME_COMMAND_HANDLER_UNDO,
    LMME_COMMAND_HANDLER_REDO,
    LMME_COMMAND_HANDLER_CUT,
    LMME_COMMAND_HANDLER_COPY,
    LMME_COMMAND_HANDLER_PASTE,
    LMME_COMMAND_HANDLER_SHOW_FIND,
    LMME_COMMAND_HANDLER_SHOW_REPLACE,
    LMME_COMMAND_HANDLER_FIND_NEXT,
    LMME_COMMAND_HANDLER_FIND_PREVIOUS,
    LMME_COMMAND_HANDLER_REPLACE_CURRENT,
    LMME_COMMAND_HANDLER_REPLACE_ALL,
    LMME_COMMAND_HANDLER_SEARCH_CLOSE,
    LMME_COMMAND_HANDLER_BOLD,
    LMME_COMMAND_HANDLER_ITALIC,
    LMME_COMMAND_HANDLER_INSERT_LINK,
    LMME_COMMAND_HANDLER_INSERT_IMAGE,
    LMME_COMMAND_HANDLER_TREE_NEW_FILE,
    LMME_COMMAND_HANDLER_TREE_NEW_FOLDER,
    LMME_COMMAND_HANDLER_TREE_RENAME,
    LMME_COMMAND_HANDLER_TREE_DELETE,
    LMME_COMMAND_HANDLER_TREE_OPEN,
    LMME_COMMAND_HANDLER_TREE_CLOSE_TAB,
    LMME_COMMAND_HANDLER_TREE_COPY_RELATIVE_PATH,
    LMME_COMMAND_HANDLER_TREE_COPY_FULL_PATH,
    LMME_COMMAND_HANDLER_TREE_COPY_IMAGE_LINK,
    LMME_COMMAND_HANDLER_TREE_OPEN_CONTAINING_FOLDER,
    LMME_COMMAND_HANDLER_COUNT
} LmmeCommandHandler;

typedef gboolean (*LmmeCommandEnabledFunc)(const LmmeApp *app);

typedef struct {
    const char *id;
    const char *action_name;
    const char *label;
    const char *help;
    LmmeCommandCategory category;
    const char *default_accels[6];
    LmmeCommandEnabledFunc is_enabled;
    LmmeCommandHandler handler;
    guint flags;
} LmmeCommandDef;

#endif
