#include "command/command_handlers.h"

LmmeCommandDomain
lmme_command_handler_domain(LmmeCommandHandler handler)
{
    switch (handler) {
    case LMME_COMMAND_HANDLER_OPEN:
    case LMME_COMMAND_HANDLER_SAVE:
    case LMME_COMMAND_HANDLER_QUIT:
        return LMME_COMMAND_DOMAIN_FILE;
    case LMME_COMMAND_HANDLER_NEW_FILE:
    case LMME_COMMAND_HANDLER_NEW_FOLDER:
    case LMME_COMMAND_HANDLER_RENAME:
    case LMME_COMMAND_HANDLER_DELETE:
    case LMME_COMMAND_HANDLER_TREE_NEW_FILE:
    case LMME_COMMAND_HANDLER_TREE_NEW_FOLDER:
    case LMME_COMMAND_HANDLER_TREE_RENAME:
    case LMME_COMMAND_HANDLER_TREE_DELETE:
    case LMME_COMMAND_HANDLER_TREE_OPEN:
    case LMME_COMMAND_HANDLER_TREE_CLOSE_TAB:
    case LMME_COMMAND_HANDLER_TREE_COPY_RELATIVE_PATH:
    case LMME_COMMAND_HANDLER_TREE_COPY_FULL_PATH:
    case LMME_COMMAND_HANDLER_TREE_COPY_IMAGE_LINK:
    case LMME_COMMAND_HANDLER_TREE_OPEN_CONTAINING_FOLDER:
        return LMME_COMMAND_DOMAIN_WORKSPACE;
    case LMME_COMMAND_HANDLER_CLOSE_TAB:
    case LMME_COMMAND_HANDLER_CLOSE_OTHER_TABS:
    case LMME_COMMAND_HANDLER_CLOSE_TABS_RIGHT:
    case LMME_COMMAND_HANDLER_CLOSE_TABS_LEFT:
    case LMME_COMMAND_HANDLER_CLOSE_ALL_TABS:
    case LMME_COMMAND_HANDLER_COPY_RELATIVE_PATH:
    case LMME_COMMAND_HANDLER_COPY_FULL_PATH:
    case LMME_COMMAND_HANDLER_NEXT_TAB:
    case LMME_COMMAND_HANDLER_PREVIOUS_TAB:
        return LMME_COMMAND_DOMAIN_DOCUMENT;
    case LMME_COMMAND_HANDLER_UNDO:
    case LMME_COMMAND_HANDLER_REDO:
    case LMME_COMMAND_HANDLER_CUT:
    case LMME_COMMAND_HANDLER_COPY:
    case LMME_COMMAND_HANDLER_PASTE:
    case LMME_COMMAND_HANDLER_SHOW_FIND:
    case LMME_COMMAND_HANDLER_SHOW_REPLACE:
    case LMME_COMMAND_HANDLER_FIND_NEXT:
    case LMME_COMMAND_HANDLER_FIND_PREVIOUS:
    case LMME_COMMAND_HANDLER_REPLACE_CURRENT:
    case LMME_COMMAND_HANDLER_REPLACE_ALL:
    case LMME_COMMAND_HANDLER_SEARCH_CLOSE:
    case LMME_COMMAND_HANDLER_BOLD:
    case LMME_COMMAND_HANDLER_ITALIC:
    case LMME_COMMAND_HANDLER_INSERT_LINK:
    case LMME_COMMAND_HANDLER_INSERT_IMAGE:
        return LMME_COMMAND_DOMAIN_EDITOR;
    case LMME_COMMAND_HANDLER_TOGGLE_SIDEBAR:
    case LMME_COMMAND_HANDLER_TOGGLE_PREVIEW:
    case LMME_COMMAND_HANDLER_ZOOM_IN:
    case LMME_COMMAND_HANDLER_ZOOM_OUT:
    case LMME_COMMAND_HANDLER_ZOOM_RESET:
    case LMME_COMMAND_HANDLER_FOCUS_MODE:
        return LMME_COMMAND_DOMAIN_VIEW;
    case LMME_COMMAND_HANDLER_COUNT:
        return LMME_COMMAND_DOMAIN_NONE;
    }

    return LMME_COMMAND_DOMAIN_NONE;
}
